version: '3.0'
services:
  haste-server:
    container_name: haste-server
    build: .
    environment:
      - STORAGE_TYPE=file
      - RECOMPRESS_STATIC_ASSETS=false
    ports:
      - 7777:7777
    volumes:
      - './upload:/usr/src/app/upload'
